### ISSUE TITLE
[request] create a broccoli task

### ISSUE THREAD

**Issue by bguiz** [aslansky/css-sprite#10]
css-sprite already has gulp and grunt tasks - could you please create a task for [broccoli](https://github.com/broccolijs/broccoli) too?

**Comment by aslansky** [comment]
in [sprity 1.0.0](https://www.npmjs.com/package/sprity) external task are moved to there own modules. so if someone wants to write a broccoli task feel free to do it.

**Comment by bguiz** [comment]
Thanks for the update - is sprity the successor to this module, css-sprite?

**Comment by aslansky** [comment]
Yes it is. There where so many changes and I never liked the name css-sprite. So it was the right time for renaming.

**Comment by bguiz** [comment]
Any plans for sprity to support SVG sprites? I have had some requests to add that feature in one of my modules that wraps css-sprite, and it would be great if sprity was able to do this.

**Comment by aslansky** [comment]
Currently I personally have no plans for doing that. But thats why I rewrote css-sprite to be as modular as possible. So maybe somebody else wants to write an image processor / style processor that can handle svg.

By the way, if you just want to have svg as an input graphic for your png/jpg sprites you could try [sprity-gm](https://www.npmjs.com/package/sprity-gm). As far as I remember GraphicsMagick is able to handle svgs.
