### ISSUE TITLE
[Request] Indentation Option for e.g. Sass

### ISSUE THREAD

**Issue by CREEATION** [aslansky/css-sprite#33]
Hello,

an "indentation" option would be cool, to keep code consistent.
Something like:

```json
{
    "indentation": {
        "type": "tab",
        "size": 4
    }
}
```

**Comment by jedmao** [comment]
@CREEATION the problem is that if you already have an EditorConfig file you have to then RE-config the indentation in the case of this tool, which is counter-productive.

@aslansky has a good point. This is definitely a case in which you would want to adopt EditorConfig settings.

**Comment by aslansky** [comment]
With [sprity 1.0.0](https://github.com/sprity/sprity) you can now configure the indentation style.

**Comment by jednano** [comment]
Thanks @aslansky!
