### ISSUE TITLE
Works from the cli but not in the code [undefined:0   TypeError: undefined is not a function]

### ISSUE THREAD

**Issue by maarekj** [aslansky/css-sprite#40]
Hello,
At me, this library works in the cli but not in the code.
When I execute

    sprite.create({style: "sprite", processor: "less", out: process.getCwd(), src:["./src/image.png"], ...});

I obtain this error:

    undefined:0

    TypeError: undefined is not a function

An idea ?

**Comment by aslansky** [comment]
Can you post some more code? How do you require css-sprite in your code? The create function should be there. You're use it exactly the same like in the tests.

**Comment by maarekj** [comment]
Sorry, I do not remember, I switched to something else.

**Comment by aslansky** [comment]
ok
