### ISSUE TITLE
sprite@2x.png + sprite.png (generated with artefacts)

### ISSUE THREAD

**Issue by t3kkitz** [aslansky/css-sprite#42]
Generated retina sprite option have defects with resize to base sprite. Also, can we just generate only retina sprite (200%) and set set sizes in '_sprite.scss' like 100% for every screen sizes?
![sprite-artefact](https://cloud.githubusercontent.com/assets/6743039/5692250/51ba7e8e-98fe-11e4-8dc8-b80ed60a88b1.png)

**Comment by mitchmalone** [comment]
+1

**Comment by farism** [comment]
Is this a bug with lwip?

**Comment by aslansky** [comment]
Yeah it is probably a lwip issue. But I didn't have the time to look into it.

**Comment by itayco** [comment]
When using the 'grid' interpolation method this issue is resolved - at least with my transparent png's.
See associated pull request.

**Comment by farism** [comment]
I don't think that this is the answer, on my particular spritesheet it looks even worse with grid. It's probably best to keep it as the default and wait for lwip to fix on their side. Or perhaps the interpolation function should be an configurable in css-sprite.

**Comment by NAlbuquerque** [comment]
This is definitely a lwip issue. I would agree with @farism and leave it as default (as it should not have artifacts in that mode) and provide a config to set the interpolation method until it's fixed.

Further discussion on the lwip issue here: https://github.com/EyalAr/lwip/issues/109

**Comment by hisnameisjimmy** [comment]
I've tried rolling back lwip to previous versions, going back to 0.0.3, and the issue persists. I'm guessing lwip has always had this problem, and switching from node canvas to lwip introduced the issue to css-sprite. 

I tried going back to css-sprite 0.8.0-beta2, which from commit history appears to be the one before the switch to lwip, but when running I hit these errors, and I can't find anything online about it:

Ignoring blurb-25.png -> Error: out of memory
Ignoring blurb-crush.png -> Error: out of memory
Ignoring blurb-optimize.png -> Error: out of memory

It'll produce the retina 2x sprite, but not the 1x, which was the whole point of reverting. Not sure if there is an easy solution to this outside of pushing on lwip to fix the issue.

**Comment by hisnameisjimmy** [comment]
It took me a week to think of this, which may speak to some kind of terrible deficit on my part, but a very easy workaround is to take the generated @2x retina sprite and just manually resize it in something like Photoshop, then save it as the @1x sprite. I did this, and everything looks great. It's not ideal, but it's way better than any other alternative I could think of (keep in mind it took me a week to think of this one, so take that with a grain of salt).
