### ISSUE TITLE
Error running "npm install css-sprite" with node 0.12.0

### ISSUE THREAD

**Issue by ricardomasao** [aslansky/css-sprite#51]
When I run "npm install", I'm getting erros:

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ricardoshigeoka/Jobs/Brastemp/Menu/node_modules/css-sprite/node_modules/gaze
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "css-sprite"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! gaze@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gaze@0.6.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the gaze package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls gaze
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

I'm running on Mac OSX Yosemite.

node version
0.12.0

**Comment by Moinax** [comment]
+1

**Comment by computersarecool** [comment]
+1

**Comment by CREEATION** [comment]
+1

**Comment by alexkaraman85** [comment]
@CREEATION - Also have this issue with node 0.10.2

[INFO] > lwip@0.0.6 install C:\Workspace\code\main\node_modules\css-sprite\node_modules\lwip
[INFO] > node-gyp rebuild
[INFO]
[INFO]
[INFO] C:\Workspace\code\main\node_modules\css-sprite\node_modules\lwip>node "C:\Workspace\code\main\node\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
[INFO] npm ERR! Windows_NT 6.1.7601
[INFO] npm ERR! argv "C:\\Workspace\\code\\main\\node
node" "C:\\Workspace\\code\\main\\node\\npm\\bin
npm-cli.js" "install" "--color=false"
[INFO] npm ERR! node v0.10.34
[INFO] npm ERR! npm v2.1.6
[INFO] npm ERR! code ELIFECYCLE
[INFO]
[INFO] npm ERR! gaze@0.6.4 install: `node-gyp rebuild`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR!
[INFO] npm ERR! Failed at the gaze@0.6.4 install script.
[INFO] npm ERR! This is most likely a problem with the gaze package,
[INFO] npm ERR! not with npm itself.
[INFO] npm ERR! Tell the author that this fails on your system:
[INFO] npm ERR! node-gyp rebuild

**Comment by alexkaraman85** [comment]
@aslansky 

Is it possible to downgrade to ```gaze@0.5.x``` until @shama fixes this.

https://github.com/shama/gaze/issues/110#issuecomment-61302737

**Comment by judewang** [comment]
@alexkaraman85 

You can try using it with node `v0.10.31`, it worked for me, too.

**Comment by ricardomasao** [comment]
Downgraded to v.0.10.31 and didn't  work

**Comment by alexkaraman85** [comment]
@ricardomasao - tried today as well and 0.10.31 did not change anything for me.  Still getting the same issue.

**Comment by ventrebleu** [comment]
+1

**Comment by cmnstmntmn** [comment]
+1

**Comment by cmnstmntmn** [comment]
you may try an older release [v0.10.29](http://nodejs.org/dist/v0.10.29/) works for me

**Comment by iboozyvoozy** [comment]
+1

**Comment by ricardomasao** [comment]
Tryed v0.10.29 and worked! 

Thanks @cmnstmntmn

**Comment by denisborovikov** [comment]
Downgrade is not resolves a problem. Current version of node.js is 0.12.0 and css-sprite should works on it.

**Comment by ricardomasao** [comment]
I closed the issue as this solves the errors reported initially. I think the right thing would be to open a new issue reporting the error in node v0.12.0. Would be clearer for everyone. @denisborovikov

**Comment by denisborovikov** [comment]
@ricardomasao The reason why you've got this error was node.js v. 0.12.0 and probably Mac OSX Yosemite (as in my case) , so issue you've opened is what we need. You may just rename it to make more clear description.

**Comment by alexkaraman85** [comment]
I'm with @denisborovikov, downgrading to an older version of Node.js is not a fix to this issue, but a work around.

**Comment by aslansky** [comment]
should be resolved with 0.9.6

**Comment by Moinax** [comment]
It's working, thanks :)

**Comment by paulstatezny** [comment]
On 0.9.0 I was able to resolve this issue by rolling back Node to 0.10.29, per the comments above.

**Comment by zjhiphop** [comment]
Mac + NodeJS v5.3.0 

+1
