### ISSUE TITLE
not compatible with node 0.12.0

### ISSUE THREAD

**Issue by mkoryak** [aslansky/css-sprite#53]
Your library uses lwip which might not be compatible with 0.12.0 - i opened an issue there:
https://github.com/EyalAr/lwip/issues/119

**Comment by aslansky** [comment]
With [sprity v1.0.0](https://github.com/sprity/sprity) you can switch between different image engines. By now [sprity-gm](https://github.com/sprity/sprity-gm) should be compatible with node 0.12 and io.js.

**Comment by aslansky** [comment]
lwip 0.0.7 was released and is now compatible with io.js. Please use sprity v1.0.4
