### ISSUE TITLE
Remove a dot from {{class}} in mustache template

### ISSUE THREAD

**Issue by denisborovikov** [aslansky/css-sprite#54]
It makes possible to create silent classes (or placeholder selectors in SASS) for preprocessors in custom templates, i.e. `%{{ class }} { ... }`.

Now this code generates `%.sprite-name { ... }`.

Expected `%sprite-name { .... }`.

**Comment by denisborovikov** [comment]
It's impossible now to get sprite identifier insider template. {{ sprite.name }} and {[ retna.name }} return the name of the sprite file with png extension, {{ class }} returns class with dot.

I'm trying to get sprite dimensions as SCSS variable, i.e. `${{ class }}: {{ px.total_width }} {{ px.total_height }}`.

**Comment by zoubin** [comment]
I'm suffering from the same problem. `{{name}}` is suffixed with the image extension, and `{{class}}` is prefixed with a dot. It would be great helpful to customize the mustache template if a property with neither  the extension nor the prefixed dot is accessible

**Comment by solome** [comment]
+1

**Comment by denisborovikov** [comment]
Seems the same issue already opened #41

**Comment by mathflair** [comment]
${{#options}}{{cssClass}}{{/options}}-{{name}} gives the same result as {{class}} but without the name.

**Comment by denisborovikov** [comment]
@mathflair It works. Thank you for workaround.

**Comment by aslansky** [comment]
In [sprity v1.0.0](https://github.com/sprity/sprity) the . is no longer part of the classname.

**Comment by zoubin** [comment]
@aslansky Thanks for your work! I'll close https://github.com/aslansky/css-sprite/pull/59
