### ISSUE TITLE
Switch back to canvas

### ISSUE THREAD

**Issue by hisnameisjimmy** [aslansky/css-sprite#62]
LWIP hasn't had a significant update in over three months and there's been no useful response to this issue: https://github.com/EyalAr/lwip/issues/109

And it is a major issue: When resizing to 1x for retina sprites, it creates ugly jaggies no matter what interpolation method is used. 

This is when it was first brought up: https://github.com/aslansky/css-sprite/issues/42

This is a breaking issue, and without the ability to revert to previous versions of css-sprite (at least I have been unable to do so), I am left without a sprite solution in my gulp workflow, which is a huge bummer. The other alternatives to css-sprite are busch league, css-sprite is by far the best and most user-friendly sprite generation method out there.

Is it insane to switch back to canvas? Is there any other way we can work around this issue in the meantime?

**Comment by aslansky** [comment]
With [sprity v1.0.0](https://github.com/sprity/sprity) you can choose between different image processing engine. Feel free to try it out :-)
