### ISSUE TITLE
cssPath struggles with special characters

### ISSUE THREAD

**Issue by hisnameisjimmy** [aslansky/css-sprite#66]
cssPath is also struggling with special characters like < and {. I am using those for templating in Django, and later using a replace for local development, but it doesn't work as the output is garbled.

For example, in my task I have:
    cssPath: '{{ STATIC_URL }}img/'

which outputs as:
    background-image: url('%7B%7B%20STATIC_URL%20%7D%7Dimg/sprite.png');

**Comment by aslansky** [comment]
The problem should be fixed in [sprity v1.0.0](https://github.com/sprity/sprity)
