### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by lbineau** [aslansky/css-sprite#70]
Hi,

I'm using css-sprite with retina (sprity seems to have big trouble with retina support and dimensions...)
The problem is, the non retina sprite is really pixelate.
Anyone has the same trouble ? (I tried on windows and mac)

Thanks.

**Comment by aslansky** [comment]
You probably have the same problems like in #42. The dimensions stuff should be fixed in sprity 1.0.4. So please give it a try with another image engine.
