### ISSUE TITLE
Under the Windows 7 installation is not successful

### ISSUE THREAD

**Issue by rayliao** [aslansky/css-sprite#71]
![qq 20150615111210](https://cloud.githubusercontent.com/assets/5601068/8152461/bc388046-134f-11e5-9a30-50a1c05dcdb2.jpg)

**Comment by littlee** [comment]
+1 我也是

**Comment by littlee** [comment]
What's pre-required on Windows 7?

**Comment by cstefan** [comment]
Same here W8.1

6457 info postuninstall css-sprite@0.9.9
6458 error lwip@0.0.6 install: `node-gyp rebuild`
6458 error Exit status 1
6459 error Failed at the lwip@0.0.6 install script.
6459 error This is most likely a problem with the lwip package,
6459 error not with npm itself.
6459 error Tell the author that this fails on your system:
6459 error     node-gyp rebuild
6459 error You can get their info via:
6459 error     npm owner ls lwip
6459 error There is likely additional logging output above.
6460 error System Windows_NT 6.2.9200
6461 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "css-sprite" "--save-dev"
6462 error cwd J:\ChromeOsBranch\Source\Chrome\Extension
6463 error node -v v0.10.28
6464 error npm -v 1.4.9
6465 error code ELIFECYCLE
6466 verbose exit [ 1, true ]

**Comment by wikieswan** [comment]
+1

**Comment by fracz** [comment]
+1

**Comment by Bogdan808** [comment]
+1
